server.port=8080
spring.application.name=T1_FeignGrupo9_Pregunta2

# Conexion a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Farmacia?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=TU_CONTRASEÑA_DE_MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update




